export default [
  {
    login: "sashadev-sky",
    id: 41092741,
    node_id: "MDQ6VXNlcjQxMDkyNzQx",
    avatar_url: "https://avatars1.githubusercontent.com/u/41092741?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/sashadev-sky",
    html_url: "https://github.com/sashadev-sky",
    followers_url: "https://api.github.com/users/sashadev-sky/followers",
    following_url:
      "https://api.github.com/users/sashadev-sky/following{/other_user}",
    gists_url: "https://api.github.com/users/sashadev-sky/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/sashadev-sky/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/sashadev-sky/subscriptions",
    organizations_url: "https://api.github.com/users/sashadev-sky/orgs",
    repos_url: "https://api.github.com/users/sashadev-sky/repos",
    events_url: "https://api.github.com/users/sashadev-sky/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/sashadev-sky/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "pushpinderpalsingh",
    id: 47032662,
    node_id: "MDQ6VXNlcjQ3MDMyNjYy",
    avatar_url: "https://avatars3.githubusercontent.com/u/47032662?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/pushpinderpalsingh",
    html_url: "https://github.com/pushpinderpalsingh",
    followers_url: "https://api.github.com/users/pushpinderpalsingh/followers",
    following_url:
      "https://api.github.com/users/pushpinderpalsingh/following{/other_user}",
    gists_url:
      "https://api.github.com/users/pushpinderpalsingh/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/pushpinderpalsingh/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/pushpinderpalsingh/subscriptions",
    organizations_url: "https://api.github.com/users/pushpinderpalsingh/orgs",
    repos_url: "https://api.github.com/users/pushpinderpalsingh/repos",
    events_url:
      "https://api.github.com/users/pushpinderpalsingh/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/pushpinderpalsingh/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "ArnavBalyan",
    id: 60175178,
    node_id: "MDQ6VXNlcjYwMTc1MTc4",
    avatar_url: "https://avatars2.githubusercontent.com/u/60175178?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/ArnavBalyan",
    html_url: "https://github.com/ArnavBalyan",
    followers_url: "https://api.github.com/users/ArnavBalyan/followers",
    following_url:
      "https://api.github.com/users/ArnavBalyan/following{/other_user}",
    gists_url: "https://api.github.com/users/ArnavBalyan/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/ArnavBalyan/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/ArnavBalyan/subscriptions",
    organizations_url: "https://api.github.com/users/ArnavBalyan/orgs",
    repos_url: "https://api.github.com/users/ArnavBalyan/repos",
    events_url: "https://api.github.com/users/ArnavBalyan/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/ArnavBalyan/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "deveshsangwan",
    id: 53528457,
    node_id: "MDQ6VXNlcjUzNTI4NDU3",
    avatar_url: "https://avatars2.githubusercontent.com/u/53528457?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/deveshsangwan",
    html_url: "https://github.com/deveshsangwan",
    followers_url: "https://api.github.com/users/deveshsangwan/followers",
    following_url:
      "https://api.github.com/users/deveshsangwan/following{/other_user}",
    gists_url: "https://api.github.com/users/deveshsangwan/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/deveshsangwan/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/deveshsangwan/subscriptions",
    organizations_url: "https://api.github.com/users/deveshsangwan/orgs",
    repos_url: "https://api.github.com/users/deveshsangwan/repos",
    events_url: "https://api.github.com/users/deveshsangwan/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/deveshsangwan/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "vini7148",
    id: 56228018,
    node_id: "MDQ6VXNlcjU2MjI4MDE4",
    avatar_url: "https://avatars1.githubusercontent.com/u/56228018?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/vini7148",
    html_url: "https://github.com/vini7148",
    followers_url: "https://api.github.com/users/vini7148/followers",
    following_url:
      "https://api.github.com/users/vini7148/following{/other_user}",
    gists_url: "https://api.github.com/users/vini7148/gists{/gist_id}",
    starred_url: "https://api.github.com/users/vini7148/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/vini7148/subscriptions",
    organizations_url: "https://api.github.com/users/vini7148/orgs",
    repos_url: "https://api.github.com/users/vini7148/repos",
    events_url: "https://api.github.com/users/vini7148/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/vini7148/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "suveb",
    id: 41081461,
    node_id: "MDQ6VXNlcjQxMDgxNDYx",
    avatar_url: "https://avatars3.githubusercontent.com/u/41081461?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/suveb",
    html_url: "https://github.com/suveb",
    followers_url: "https://api.github.com/users/suveb/followers",
    following_url: "https://api.github.com/users/suveb/following{/other_user}",
    gists_url: "https://api.github.com/users/suveb/gists{/gist_id}",
    starred_url: "https://api.github.com/users/suveb/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/suveb/subscriptions",
    organizations_url: "https://api.github.com/users/suveb/orgs",
    repos_url: "https://api.github.com/users/suveb/repos",
    events_url: "https://api.github.com/users/suveb/events{/privacy}",
    received_events_url: "https://api.github.com/users/suveb/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "sonu5433",
    id: 64070435,
    node_id: "MDQ6VXNlcjY0MDcwNDM1",
    avatar_url: "https://avatars2.githubusercontent.com/u/64070435?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/sonu5433",
    html_url: "https://github.com/sonu5433",
    followers_url: "https://api.github.com/users/sonu5433/followers",
    following_url:
      "https://api.github.com/users/sonu5433/following{/other_user}",
    gists_url: "https://api.github.com/users/sonu5433/gists{/gist_id}",
    starred_url: "https://api.github.com/users/sonu5433/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/sonu5433/subscriptions",
    organizations_url: "https://api.github.com/users/sonu5433/orgs",
    repos_url: "https://api.github.com/users/sonu5433/repos",
    events_url: "https://api.github.com/users/sonu5433/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/sonu5433/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "jlsjefferson",
    id: 53836950,
    node_id: "MDQ6VXNlcjUzODM2OTUw",
    avatar_url: "https://avatars3.githubusercontent.com/u/53836950?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/jlsjefferson",
    html_url: "https://github.com/jlsjefferson",
    followers_url: "https://api.github.com/users/jlsjefferson/followers",
    following_url:
      "https://api.github.com/users/jlsjefferson/following{/other_user}",
    gists_url: "https://api.github.com/users/jlsjefferson/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/jlsjefferson/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/jlsjefferson/subscriptions",
    organizations_url: "https://api.github.com/users/jlsjefferson/orgs",
    repos_url: "https://api.github.com/users/jlsjefferson/repos",
    events_url: "https://api.github.com/users/jlsjefferson/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/jlsjefferson/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "NITIN3299",
    id: 53136789,
    node_id: "MDQ6VXNlcjUzMTM2Nzg5",
    avatar_url: "https://avatars3.githubusercontent.com/u/53136789?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/NITIN3299",
    html_url: "https://github.com/NITIN3299",
    followers_url: "https://api.github.com/users/NITIN3299/followers",
    following_url:
      "https://api.github.com/users/NITIN3299/following{/other_user}",
    gists_url: "https://api.github.com/users/NITIN3299/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/NITIN3299/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/NITIN3299/subscriptions",
    organizations_url: "https://api.github.com/users/NITIN3299/orgs",
    repos_url: "https://api.github.com/users/NITIN3299/repos",
    events_url: "https://api.github.com/users/NITIN3299/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/NITIN3299/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "drajwal1511",
    id: 44205030,
    node_id: "MDQ6VXNlcjQ0MjA1MDMw",
    avatar_url: "https://avatars2.githubusercontent.com/u/44205030?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/drajwal1511",
    html_url: "https://github.com/drajwal1511",
    followers_url: "https://api.github.com/users/drajwal1511/followers",
    following_url:
      "https://api.github.com/users/drajwal1511/following{/other_user}",
    gists_url: "https://api.github.com/users/drajwal1511/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/drajwal1511/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/drajwal1511/subscriptions",
    organizations_url: "https://api.github.com/users/drajwal1511/orgs",
    repos_url: "https://api.github.com/users/drajwal1511/repos",
    events_url: "https://api.github.com/users/drajwal1511/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/drajwal1511/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "Ritik488",
    id: 51055745,
    node_id: "MDQ6VXNlcjUxMDU1NzQ1",
    avatar_url: "https://avatars3.githubusercontent.com/u/51055745?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Ritik488",
    html_url: "https://github.com/Ritik488",
    followers_url: "https://api.github.com/users/Ritik488/followers",
    following_url:
      "https://api.github.com/users/Ritik488/following{/other_user}",
    gists_url: "https://api.github.com/users/Ritik488/gists{/gist_id}",
    starred_url: "https://api.github.com/users/Ritik488/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/Ritik488/subscriptions",
    organizations_url: "https://api.github.com/users/Ritik488/orgs",
    repos_url: "https://api.github.com/users/Ritik488/repos",
    events_url: "https://api.github.com/users/Ritik488/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/Ritik488/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "AbhishekKumarSingh00",
    id: 51472345,
    node_id: "MDQ6VXNlcjUxNDcyMzQ1",
    avatar_url: "https://avatars1.githubusercontent.com/u/51472345?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/AbhishekKumarSingh00",
    html_url: "https://github.com/AbhishekKumarSingh00",
    followers_url:
      "https://api.github.com/users/AbhishekKumarSingh00/followers",
    following_url:
      "https://api.github.com/users/AbhishekKumarSingh00/following{/other_user}",
    gists_url:
      "https://api.github.com/users/AbhishekKumarSingh00/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/AbhishekKumarSingh00/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/AbhishekKumarSingh00/subscriptions",
    organizations_url: "https://api.github.com/users/AbhishekKumarSingh00/orgs",
    repos_url: "https://api.github.com/users/AbhishekKumarSingh00/repos",
    events_url:
      "https://api.github.com/users/AbhishekKumarSingh00/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/AbhishekKumarSingh00/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "akshanshnain",
    id: 64038139,
    node_id: "MDQ6VXNlcjY0MDM4MTM5",
    avatar_url: "https://avatars1.githubusercontent.com/u/64038139?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/akshanshnain",
    html_url: "https://github.com/akshanshnain",
    followers_url: "https://api.github.com/users/akshanshnain/followers",
    following_url:
      "https://api.github.com/users/akshanshnain/following{/other_user}",
    gists_url: "https://api.github.com/users/akshanshnain/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/akshanshnain/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/akshanshnain/subscriptions",
    organizations_url: "https://api.github.com/users/akshanshnain/orgs",
    repos_url: "https://api.github.com/users/akshanshnain/repos",
    events_url: "https://api.github.com/users/akshanshnain/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/akshanshnain/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "gauravkr10184",
    id: 65072563,
    node_id: "MDQ6VXNlcjY1MDcyNTYz",
    avatar_url: "https://avatars0.githubusercontent.com/u/65072563?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/gauravkr10184",
    html_url: "https://github.com/gauravkr10184",
    followers_url: "https://api.github.com/users/gauravkr10184/followers",
    following_url:
      "https://api.github.com/users/gauravkr10184/following{/other_user}",
    gists_url: "https://api.github.com/users/gauravkr10184/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/gauravkr10184/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/gauravkr10184/subscriptions",
    organizations_url: "https://api.github.com/users/gauravkr10184/orgs",
    repos_url: "https://api.github.com/users/gauravkr10184/repos",
    events_url: "https://api.github.com/users/gauravkr10184/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/gauravkr10184/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "vivolscute",
    id: 55041874,
    node_id: "MDQ6VXNlcjU1MDQxODc0",
    avatar_url: "https://avatars3.githubusercontent.com/u/55041874?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/vivolscute",
    html_url: "https://github.com/vivolscute",
    followers_url: "https://api.github.com/users/vivolscute/followers",
    following_url:
      "https://api.github.com/users/vivolscute/following{/other_user}",
    gists_url: "https://api.github.com/users/vivolscute/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/vivolscute/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/vivolscute/subscriptions",
    organizations_url: "https://api.github.com/users/vivolscute/orgs",
    repos_url: "https://api.github.com/users/vivolscute/repos",
    events_url: "https://api.github.com/users/vivolscute/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/vivolscute/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "chirag-goel360",
    id: 61325696,
    node_id: "MDQ6VXNlcjYxMzI1Njk2",
    avatar_url: "https://avatars3.githubusercontent.com/u/61325696?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/chirag-goel360",
    html_url: "https://github.com/chirag-goel360",
    followers_url: "https://api.github.com/users/chirag-goel360/followers",
    following_url:
      "https://api.github.com/users/chirag-goel360/following{/other_user}",
    gists_url: "https://api.github.com/users/chirag-goel360/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/chirag-goel360/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/chirag-goel360/subscriptions",
    organizations_url: "https://api.github.com/users/chirag-goel360/orgs",
    repos_url: "https://api.github.com/users/chirag-goel360/repos",
    events_url: "https://api.github.com/users/chirag-goel360/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/chirag-goel360/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "Samrat-Bhardwaj",
    id: 68969450,
    node_id: "MDQ6VXNlcjY4OTY5NDUw",
    avatar_url: "https://avatars2.githubusercontent.com/u/68969450?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Samrat-Bhardwaj",
    html_url: "https://github.com/Samrat-Bhardwaj",
    followers_url: "https://api.github.com/users/Samrat-Bhardwaj/followers",
    following_url:
      "https://api.github.com/users/Samrat-Bhardwaj/following{/other_user}",
    gists_url: "https://api.github.com/users/Samrat-Bhardwaj/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/Samrat-Bhardwaj/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/Samrat-Bhardwaj/subscriptions",
    organizations_url: "https://api.github.com/users/Samrat-Bhardwaj/orgs",
    repos_url: "https://api.github.com/users/Samrat-Bhardwaj/repos",
    events_url: "https://api.github.com/users/Samrat-Bhardwaj/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/Samrat-Bhardwaj/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "SlimShady15042000",
    id: 63352653,
    node_id: "MDQ6VXNlcjYzMzUyNjUz",
    avatar_url: "https://avatars1.githubusercontent.com/u/63352653?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/SlimShady15042000",
    html_url: "https://github.com/SlimShady15042000",
    followers_url: "https://api.github.com/users/SlimShady15042000/followers",
    following_url:
      "https://api.github.com/users/SlimShady15042000/following{/other_user}",
    gists_url: "https://api.github.com/users/SlimShady15042000/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/SlimShady15042000/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/SlimShady15042000/subscriptions",
    organizations_url: "https://api.github.com/users/SlimShady15042000/orgs",
    repos_url: "https://api.github.com/users/SlimShady15042000/repos",
    events_url:
      "https://api.github.com/users/SlimShady15042000/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/SlimShady15042000/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "aslynatilla",
    id: 15921362,
    node_id: "MDQ6VXNlcjE1OTIxMzYy",
    avatar_url: "https://avatars3.githubusercontent.com/u/15921362?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/aslynatilla",
    html_url: "https://github.com/aslynatilla",
    followers_url: "https://api.github.com/users/aslynatilla/followers",
    following_url:
      "https://api.github.com/users/aslynatilla/following{/other_user}",
    gists_url: "https://api.github.com/users/aslynatilla/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/aslynatilla/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/aslynatilla/subscriptions",
    organizations_url: "https://api.github.com/users/aslynatilla/orgs",
    repos_url: "https://api.github.com/users/aslynatilla/repos",
    events_url: "https://api.github.com/users/aslynatilla/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/aslynatilla/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "Pawner818",
    id: 57907431,
    node_id: "MDQ6VXNlcjU3OTA3NDMx",
    avatar_url: "https://avatars1.githubusercontent.com/u/57907431?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Pawner818",
    html_url: "https://github.com/Pawner818",
    followers_url: "https://api.github.com/users/Pawner818/followers",
    following_url:
      "https://api.github.com/users/Pawner818/following{/other_user}",
    gists_url: "https://api.github.com/users/Pawner818/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/Pawner818/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/Pawner818/subscriptions",
    organizations_url: "https://api.github.com/users/Pawner818/orgs",
    repos_url: "https://api.github.com/users/Pawner818/repos",
    events_url: "https://api.github.com/users/Pawner818/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/Pawner818/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "client69",
    id: 72541033,
    node_id: "MDQ6VXNlcjcyNTQxMDMz",
    avatar_url: "https://avatars2.githubusercontent.com/u/72541033?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/client69",
    html_url: "https://github.com/client69",
    followers_url: "https://api.github.com/users/client69/followers",
    following_url:
      "https://api.github.com/users/client69/following{/other_user}",
    gists_url: "https://api.github.com/users/client69/gists{/gist_id}",
    starred_url: "https://api.github.com/users/client69/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/client69/subscriptions",
    organizations_url: "https://api.github.com/users/client69/orgs",
    repos_url: "https://api.github.com/users/client69/repos",
    events_url: "https://api.github.com/users/client69/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/client69/received_events",
    type: "User",
    site_admin: false,
  },
];
