export default {
  login: "sachuverma",
  id: 43083013,
  node_id: "MDQ6VXNlcjQzMDgzMDEz",
  avatar_url: "https://avatars0.githubusercontent.com/u/43083013?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/sachuverma",
  html_url: "https://github.com/sachuverma",
  followers_url: "https://api.github.com/users/sachuverma/followers",
  following_url:
    "https://api.github.com/users/sachuverma/following{/other_user}",
  gists_url: "https://api.github.com/users/sachuverma/gists{/gist_id}",
  starred_url: "https://api.github.com/users/sachuverma/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/sachuverma/subscriptions",
  organizations_url: "https://api.github.com/users/sachuverma/orgs",
  repos_url: "https://api.github.com/users/sachuverma/repos",
  events_url: "https://api.github.com/users/sachuverma/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/sachuverma/received_events",
  type: "User",
  site_admin: false,
  name: "sachin verma",
  company: null,
  blog: "",
  location: "New Delhi, India",
  email: null,
  hireable: true,
  bio:
    "An aspiring web developer with\r\n    | excellent problem solving skills\r\n    | passionate about learning \r\n    | good at what I do",
  twitter_username: null,
  public_repos: 43,
  public_gists: 1,
  followers: 21,
  following: 48,
  created_at: "2018-09-08T02:43:42Z",
  updated_at: "2021-01-18T18:04:41Z",
};
